version: '3'

services:
  web:
    build: .
    restart: 'always'
    ports:
      - '80:8080'
    volumes:
      - .:/project
    command: sh -c "python3 chatapp/main.py"
    links:
      - postgres
    networks:
      - default
      - database_bridge

  local:
    build: .
    restart: 'always'
    ports:
      - '80:8080'
    volumes:
      - .:/project
    command: sh -c "adev runserver chatapp/main.py"
    links:
      - postgres
    networks:
      - default
      - database_bridge
    

  postgres:
    image: postgres:latest
    env_file: '.postgresqlenv'
    restart: 'always'
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - database_bridge
      
volumes:
  # postgres data
  pgdata: {}

networks:
  # bridge db-web
  database_bridge: {}
